apiVersion: v1
kind: ServiceAccount
metadata:
  name: mobile-app-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::697551514015:role/vmcm-eks-mobile-app-irsa
    eks.amazonaws.com/token-expiration: "86400"